name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in mynotes
        run: ls -la ./  # List files in the mynotes directory

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: myacr5081850.azurecr.io
          username: ${{ secrets.AZURE_USERNAME }}
          password: ${{ secrets.AZURE_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and push Docker images
        run: |
          # Build the images using docker-compose
          docker-compose -f mynotes/docker-compose.yml build
          #docker-compose -f ./

          # Tag the images for ACR
          docker tag  myacr5081850.azurecr.io/django_cont:latest
          docker tag nginx_cont myacr5081850.azurecr.io/nginx:latest

          # Push the images to ACR
          docker push myacr5081850.azurecr.io/django_cont:latest
          docker push myacr5081850.azurecr.io/nginx_cont:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure CLI
        uses: azure/setup-cli@v1

      - name: Log in to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Container Apps
        run: |
            az containerapp update --name mycontainerappenv \
            --resource-group myResourceGroup \
            --image myacr5081850.azurecr.io/note-app:latest
